## 背景: 
- 具備按軸自動或顯示數據對齊功能的數據結構
- 集成時間序列功能
- 處理非時間序列數據
- 數學運算和約簡，根據不同的元數據(軸編號)執行
- 靈活處理缺失數據
- 合併及其他出現在常見數據庫中的關係型運算


## pandas 引入約定

In [2]:
from pandas import Series, DataFrame
import pandas as pd

## 主要數據結構
- Series
- DataFrame

### Series
- 類似於一維數組的對象，由一組數據(各種NumPy數據類型)以及一組與之相關的數據標籤(即索引)組成

In [6]:
# 左邊: 索引。    若無為數據指定索引，則自動創建0~N-1的整數型索引
# 右邊: 值
obj = Series([5, 7, -5, 3])
obj

0    5
1    7
2   -5
3    3
dtype: int64

In [8]:
# 數組表示形式
obj.values

array([ 5,  7, -5,  3])

In [12]:
# 數組索引對象
obj.index

RangeIndex(start=0, stop=4, step=1)

In [17]:
# 指定索引
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [18]:
# 透過索引的方式選取series中的單個值:
obj2['a']

-5

In [25]:
# 透過索引的方式選取series中的一組值:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    4
dtype: int64

In [23]:
# 透過索引的方式指定series中的單個或一組值:
obj2['b'] = 6
obj2

d    4
b    6
a   -5
c    3
dtype: int64

In [27]:
# NumPy數組運算(如根據布林型數組進行過濾、標量乘法、應用數學函數等)都會保留索引與值之間的鍊接
obj2[obj2 > 0]

d    4
b    6
c    3
dtype: int64

In [28]:
obj * 2

0    10
1    14
2   -10
3     6
b    12
dtype: int64

In [32]:
import numpy as np
np.exp(obj2)

d     54.598150
b    403.428793
a      0.006738
c     20.085537
dtype: float64

In [33]:
# 將Series看成是一個定長的有序字典(dictionary)，索引值到數據值的一個映射
'b' in obj2

True

In [34]:
# 直接透過字典創建Series
# 若只傳入一個字典，則結果Series中的索引就是原字典的健(key)(有序排列)
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [35]:
# sdata中跟states索引相匹配的那3個值會被找出來並放到相應的位置上；缺失值則使用NaN(not a number)表示
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

#### 檢測缺失數據(後)

In [36]:
# pandas: isnull() 檢測缺失數據
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [37]:
# pandas: notnull() 檢測缺失數據
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [39]:
# Series: isnull() 檢測缺失數據
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

#### 對齊不同索引數據(後)

In [40]:
# 在算術運算中自動對齊不同索引的數據
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [41]:
# Series對象本身及其索引都有一個name屬性
obj4.name = 'population'
obj.index.name = 'state'
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [47]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      5
Steve    7
Jeff    -5
Ryan     3
lolo     6
dtype: int64

### DataFrame
- 表格型的數據結構
- 包含一組有序的列，每列可以是不同的值類型(數值、字符串、布林值等)
- 有行索引與列索引，可以看成是由Series組成的字典(更用同一個索引)
- 內部的數據是以一個或多個二維塊存放(而不是列表、字典或別的一維數據結構)+

In [51]:
# 建構DataFrame: 傳入一個由等長列表(list)或NumPy數組組成的字典
# DataFrame會自動加上索引(與Series一樣)，且全部列會被有序排列
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2001, 2002],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [52]:
# 若指令了列序列，則將會按照指令順序進行排列
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [54]:
# 與Series相同，若傳入的列在數據中找不到，則產生NaN
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                  index=['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [55]:
# 獲取列資訊
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [56]:
# 透過字典標記的方式或屬性的方式，將DataFrame的列獲取為一個Series
# 返回的Series擁有原DataFrame相同的索引，且其name屬性也已經被相應地設置好了
# 與frame2.state得到相同結果
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [59]:
# 行資訊可以透過位置或名稱的方式獲得，譬如用索引字段ix
frame2.ix['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [61]:
# 列可以透過賦值的方式進行修改
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [63]:
frame2['debt'] = np.arange(5.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [64]:
# 將列表或數組賦值給某列時，其長度必須跟DataFrame的長度相匹配。
# 若使用Series進行賦值，則將與DataFrame的索引進行精確匹配，且自動填入缺失值
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [73]:
# 為不存在的列賦值，會創建出一個新列
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False

In [74]:
# del用於刪除列
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [ ]:
# 通過索引方式返回的列只是相應數據的視圖而已，對返回的Series所做的任何修改皆會反應到源DataFrame上
# 透過Series的cop方法即可顯示地複製列

In [76]:
# 使用嵌套字典(字典的字典)，創建DataFrame；外層字典的健作為列，內層健作為行索引
# 內層字典的健會被合併、排序以形成最終的索引
pop = {'Nevada': {2001: 2.4, 2002:2.9},
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [77]:
# 將frame進行轉置
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [83]:
# 若顯示指定索引，則只會顯示指定索引的相關資料
DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [84]:
# 使用Series組成的字典，創建DataFrame
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

|類型|說明|
|----|---|
|二維ndarray|數據陣列，還可以傳入行標和列標|
|由數組、列表或元祖組成的字典|每個序列會變成DataFrame的一列。所有序列的長度必須相同|
|NumPy的結構化/紀錄數組|類似於"由數組組成的字典"|
|由Series組成的字典|每個Series會成為一列。如果沒有顯示指定索引，則個Series的索引會被合併成結果的行索引|
|由字典組成的字典|各內層字典會變成一列。鍵會被合併成結果的行索引，跟"由Series組成的字典"的情況一樣|
|字典或Series的列表|各項將會成為DataFrame的一行。字典鍵或Series索引的並集將會成為DataFrame的列標|
|由列表或元組組成的列表|類似於"二維ndarray"|
|另一個DataFrame|該DataFrame的索引將被沿用，除非顯示指定了其他索引|
|NumPy的MaskedArray|類似於"二維ndarray"的情況，只是掩碼值在結果DataFrame會變成缺失值|



In [85]:
# 若設置DataFrame的index和columns的name屬性，則這些信息將會被顯示出來
frame3.index.name ='year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [86]:
# 與Series相同，values屬性也會以二維ndarray的形式返回DataFrame中的數據
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [87]:
# 若DataFrame各列的數據類型不同，則值數組的數據類型就會選用能兼容所有列的數據類型
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

### 索引對象
- pandas的索引對象負責管理軸標籤和其他元數據(譬如軸名稱等)
- 建構Series或DataFrame時，所用到的任何數組或其他序列的標籤都會被轉換成一個Index
- Index對象是不可修改的(immutable)，此特性讓Index對象在多個數據結構之千安全共享
- Index可以被繼承從而實踐特別的軸索引功能

In [88]:
obj = Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index([u'a', u'b', u'c'], dtype='object')

In [89]:
index[1:]

Index([u'b', u'c'], dtype='object')

#### pandas中主要的Index對象
|類|說明|
|--|----|
|Index|最泛化的Index對象，將軸標籤表示為一個由Python對象組成的NumPy數組|
|Int64Index|針對整數的特殊Index|
|MultiIndex|"層次化"索引對象表示單個軸上的多層索引。可以看作由元組組成的數組|
|DatatimeIndex|存儲奈秒級時間戳(用NumPy的datetime63類型表示)|
|PeriodIndex|針對Period數據(時間間隔)的特殊Index|

In [92]:
# Index的功能類似一個固定大小的集合
'Ohio' in frame3.columns

True

#### Index的方法和屬性
|方法|說明|
|----|---|
|append|連接另一個Index對象，產生一個新的Index|
|diff|計算差集，並得到一個Index|
|intersection|計算交集|
|union|計算並集|
|isin|計算一個指示各值是否都包含在參數集合中的布林型數組|
|delete|刪除索引i處的元素，並得到新的Index|
|drop|刪除傳入的值，並得到新的Index|
|insert|將元素插入到索引i處，並得到新的Index|
|is_monotonic|當各元素缺大於等於錢一個元素時，返回True|
|is_unique|當Index沒有重複值時，返回True|
|unique|計算Index中唯一值的數組|

## 基本功能

### 重新索引
- pandas對象的重要方法reindex，其作用是創建一個適應新索引的新對象

In [93]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [94]:
# Series的reindex將會根據新索引進行重排。若某索引值當前不存在，就引入缺失值
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [95]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [98]:
# 對於時間序列這樣的有序數據，重新索引時可能需要做一些插值處理。
# method選項可以達成上述目的
# 例如，使用ffill可以實現前項值填充
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

#### reindex的(插值)method選項
|參數|說明|
|----|---|
|ffill或pad|前向填充(或搬運)值|
|bfill或backfill|後向填充(或搬運)值|

In [106]:
# 對於DataFrame, reindex可以修改(行)索引、列或兩個都修改。如果僅傳入一個序列，則會重新索引行
frame = DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'],
                 columns=['Ohio', 'Texas', 'California']) 
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [101]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  Californua
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [107]:
# 使用columns關鍵字即可重新索引列
states = ['Texas', 'Utat', 'California']
frame.reindex(columns=states)

Texas  Utat  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [108]:
# 同時對行與列進行重新索引，而插值則只能按行應用
frame.reindex(index=['a', 'b', 'c', 'd'], method='ffill',
             columns=states)

Texas  Utat  California
a      1   NaN           2
b      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [110]:
# 利用ix的標籤索引功能，重新索引任務可以變得更簡潔
frame.ix[['a', 'b', 'c', 'd'], states]

Texas  Utat  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

#### reindex函數的各參數及說明

|參數|說明|
|----|---|
|index|用作索引的新序列。既可以是Index實例，也可以是其他序列型的Python數據結構。Index會被完全使用，就像沒有任何複製一樣|
|method|插值(填充)方式|
|fill_value|在重新索引的過程中，需要引入缺失值時使用的替代值|
|limit|前向或後向填充時的最大填充值|
|level|在MultiIndex的指定級別上匹配簡單索引，否則選取其子集|
|copy|默認為True，無論如何都複製：如果為False，則新舊相等就不複製|

#### 丟棄指定軸上的項
- 使用一個索引數組，或者列表，即可丟棄某條軸上的一個或多個項
- 透過drop方法返回一個在指定軸上刪除指定值後的新對象，達成執行一些數據整理和集合邏輯

In [111]:
obj = Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [112]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [113]:
# 對於DataFrame，可以刪除任意軸上的索引值
data = DataFrame(np.arange(16).reshape((4, 4)),
                index=['Ohio', 'Colorado', 'Utah', 'New York'],
                columns=['one', 'two', 'three', 'four'])
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [114]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [116]:
data.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

#### 索引、選取和過濾
- Series索引(obj[...])的工作方式類似於NumPy數組的索引，只不過Series的索引值不只是整數

In [119]:
obj = Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [120]:
obj['b']

1.0

In [121]:
obj[1]

1.0

In [122]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [123]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [124]:
# 利用標籤的切片運算與普通的Python切片運算不同，其末端是包含的(inclusive)
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [125]:
# 設置方式
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [126]:
# 對DataFrame進行索引其實就是或許一個或多個列
data = DataFrame(np.arange(16).reshape((4, 4)),
                index=['Ohio', 'Colorado', 'Utah', 'New York'],
                columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [127]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [130]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [131]:
# 透過切片進行取行
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [132]:
# 透過布林數組進行取行
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [133]:
# 透過布林型DataFrame進行索引
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [135]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [136]:
# 為了在DataFrame的行上進行標籤索引，引入專門的索引字段ix，
# 以便通過NumPy的標記法以及軸標籤從DataFrame中選取行和列的子集
data.ix['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [137]:
data.ix[['Colorado', 'Utah'], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [138]:
data.ix[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [139]:
data.ix[data.three > 5, :3]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14